[package]
name = "ucr-webrtc"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.22.1"
bytes = "=1.12.1"
openssl = "=0.10.81"
tokio = { version = "=1.53.1", features = ["rt-multi-thread", "sync", "time"] }
webrtc = "=0.17.2"
zeroize = { version = "=1.9.0", features = ["derive"] }
ucr-model = { path = "../ucr-model" }
ucr-protocol = { path = "../ucr-protocol" }

[lints]
workspace = true
