[package]
name = "ucr-webrtc"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.22.1"
openssl = "=0.10.81"
zeroize = { version = "=1.8.2", features = ["zeroize_derive"] }
ucr-model = { path = "../ucr-model" }
ucr-protocol = { path = "../ucr-protocol" }

[lints]
workspace = true
