[package]
name = "ucr-storage-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ucr-core = { path = "../ucr-core" }
ucr-model = { path = "../ucr-model" }
ucr-protocol = { path = "../ucr-protocol" }

[lints]
workspace = true
