import process from "node:process";
import { randomUUID } from "node:crypto";
const b64=(v)=>Buffer.from(v,"utf8").toString("base64");
function validateBaseUrl(v){const u=new URL(v.replace(/\/$/,""));const loop=["127.0.0.1","localhost","[::1]"].includes(u.hostname);if(u.protocol!=="https:"&&!(u.protocol==="http:"&&loop))throw new Error("UCR_BASE_URL must use HTTPS outside loopback development");return u.toString().replace(/\/$/,"")}
function config(){const n=["UCR_BASE_URL","UCR_ACCESS_TOKEN","UCR_TENANT_ID","UCR_INTEGRATION_ID"],m=n.filter(x=>!process.env[x]);if(m.length)throw new Error("missing environment: "+m.join(", "));const c=Object.fromEntries(n.map(x=>[x,process.env[x]]));c.UCR_BASE_URL=validateBaseUrl(c.UCR_BASE_URL);return c}
async function post(cfg,path,body,fetchImpl=fetch){const r=await fetchImpl(cfg.UCR_BASE_URL+path,{method:"POST",redirect:"error",headers:{authorization:`Bearer ${cfg.UCR_ACCESS_TOKEN}`,"content-type":"application/json"},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(`${path}: HTTP ${r.status}: ${JSON.stringify(v)}`);return v}
export function flowPayloads(cfg,nowMs=Date.now(),runId=randomUUID()){const scope={tenant_id:cfg.UCR_TENANT_ID},integrationId=cfg.UCR_INTEGRATION_ID,prefix=`reference-${runId}`;return{scope,integrationId,prefix,create:{scope,integration_id:integrationId,external_conference_id_b64:b64(prefix),idempotency_key:prefix+"-create",mode:"webinar",schedule:{starts_at_unix_ms:nowMs+300000,planned_end_unix_ms:nowMs+3900000,join_before_seconds:900,join_after_seconds:300,timezone:"UTC"}}}}
export async function executeFlow(cfg,transport=post,nowMs,runId){const{scope,integrationId,prefix,create}=flowPayloads(cfg,nowMs,runId);const c=(await transport(cfg,"/v1/conferences",create)).conference,cid=c.conference_id;for(const [u,r] of [["owner","owner"],["attendee","attendee"]]){await transport(cfg,"/v1/participants",{scope,conference_id:cid,integration_id:integrationId,external_user_id_b64:b64(prefix+"-"+u),role:r,idempotency_key:prefix+"-"+u});await transport(cfg,"/v1/participant-devices",{scope,conference_id:cid,integration_id:integrationId,external_user_id_b64:b64(prefix+"-"+u),idempotency_key:prefix+"-"+u+"-device"})}await transport(cfg,"/v1/conferences/runtime",{scope,conference_id:cid,integration_id:integrationId,idempotency_key:prefix+"-runtime"});for(const target of["waiting","live"])await transport(cfg,"/v1/conferences/lifecycle",{scope,conference_id:cid,integration_id:integrationId,target,idempotency_key:prefix+"-"+target});const g=(await transport(cfg,"/v1/join-grants",{scope,conference_id:cid,integration_id:integrationId,external_user_id_b64:b64(prefix+"-attendee"),ttl_seconds:900,use_policy:"single_use",idempotency_key:prefix+"-join"})).grant;return{conference_id:cid,join_url:g.join_url}}
async function selfTest(){const cfg={UCR_BASE_URL:"https://ucr.example",UCR_ACCESS_TOKEN:"token",UCR_TENANT_ID:"tenant",UCR_INTEGRATION_ID:"integration"},calls=[];const fake=async(c,p,b)=>{calls.push([p,b]);if(p==="/v1/conferences")return{conference:{conference_id:"conference-1"}};if(p==="/v1/join-grants")return{grant:{join_url:"https://join.example/#ucr_join=opaque"}};return{ok:true}};const r=await executeFlow(cfg,fake,1700000000000,"selftest");if(r.conference_id!=="conference-1"||!r.join_url.includes("#ucr_join="))throw new Error("flow drift");const expected=["/v1/conferences","/v1/participants","/v1/participant-devices","/v1/participants","/v1/participant-devices","/v1/conferences/runtime","/v1/conferences/lifecycle","/v1/conferences/lifecycle","/v1/join-grants"];if(JSON.stringify(calls.map(x=>x[0]))!==JSON.stringify(expected))throw new Error("operation order drift");let blocked=false;try{validateBaseUrl("http://public.example")}catch{blocked=true}if(!blocked)throw new Error("plaintext public URL accepted");console.log("reference Node integration self-test: PASS")}
if(process.argv.includes("--self-test"))await selfTest();else process.stdout.write(JSON.stringify(await executeFlow(config()))+"\n");
