[package]
name = "ucr-realtime-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "ucr-realtime-web"
path = "src/main.rs"

[dependencies]
axum = "=0.8.9"
base64 = "=0.22.1"
prost = "=0.14.4"
serde = { version = "=1.0.229", features = ["derive"] }
tokio = { version = "=1.53.1", features = ["macros", "net", "rt-multi-thread", "sync"] }
tokio-stream = "=0.1.17"
tonic = { version = "=0.14.6", features = ["transport"] }
ucr-api-grpc = { path = "../ucr-api-grpc" }

[lints]
workspace = true
