[package]
name = "ucr-dev"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "ucr"
path = "src/main.rs"

[dependencies]
tokio = { version = "=1.53.1", features = ["macros", "net", "rt-multi-thread", "time"] }
tokio-stream = { version = "=0.1.17", features = ["net"] }
tonic = { version = "=0.14.6", features = ["transport"] }
ucr-api-grpc = { path = "../ucr-api-grpc" }
ucr-core = { path = "../ucr-core" }
ucr-model = { path = "../ucr-model" }
ucr-protocol = { path = "../ucr-protocol" }
ucr-storage-memory = { path = "../ucr-storage-memory" }

[lints]
workspace = true
