[package]
name = "ucr-realtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.22.1"
hmac = "=0.12.1"
sha2 = "=0.10.9"
tokio = { version = "=1.53.1", features = ["sync"] }
ucr-core = { path = "../ucr-core" }
ucr-model = { path = "../ucr-model" }
ucr-sfu = { path = "../ucr-sfu" }

[lints]
workspace = true
